FROM tomcat:7-jre7

MAINTAINER limin mli@yihecloud.com

WORKDIR /program

COPY target/HackerTopic1-0.0.1-SNAPSHOT.jar /program/HackerTopic1.jar

#CMD ["java","-jar","/program/HackerTopic1.jar"]
